export const USERNAME_MAX_LENGTH = 35;
export const EMAIL_MAX_LENGTH = 60;
export const REPO_NAME_MAX_LENGTH = 35;
export const REPO_DESCRIPTION_MAX_LENGTH = 100;
export const USERNAME_TYPE = `VARCHAR(${USERNAME_MAX_LENGTH})`;
export const EMAIL_TYPE = `VARCHAR(${EMAIL_MAX_LENGTH})`;
export const REPO_NAME_TYPE = `VARCHAR(${REPO_NAME_MAX_LENGTH})`;
export const REPO_DESCRIPTION_TYPE = `VARCHAR(${REPO_DESCRIPTION_MAX_LENGTH})`;
